### ISSUE TITLE
Any changes between xcomponent-demo & zoid?

### ISSUE THREAD

**Issue by yoshprogrammer** [krakenjs/zoid-demo#2]
Hey guys,

I know you recently renamed the XComponent to Zoid - https://github.com/krakenjs/zoid

Just wanted to verify that nothing has materially changed between this xcomponent demo and Zoid (with latest update to the Zoid repo being 15 days ago and this repo being late November, 2017) before using this as a starting point for a more unified/bundled build of a React component + zoid as outlined at the end of this medium post - https://medium.com/@bluepnume/creating-a-cross-domain-react-component-with-xcomponent-fbcccc4778fd

Specifically, creating a component & bundling it with Zoid to produce my equivalent of:
```
<script src="https://www.your-site.com/loginComponent.js"></script>
<script>
   MyLoginZoidComponent.render({ ... }, '#container');
</script>
```

Cheers!

**Comment by bluepnume** [comment]
Hey! I finally had the chance to upgrade xcomponent-demo to https://github.com/krakenjs/zoid-demo -- none of the above has changed.

**Comment by muhaimincs** [comment]
how do I start? what file to get to host somewhere?
