### ISSUE TITLE
unable to run demo

### ISSUE THREAD

**Issue by jsebrech** [krakenjs/zoid-demo#4]
When I run `npm run demo` I get the following output:

```
> xcomponent-demo@1.0.3 demo C:\digipolis\prototypes\zoid-demo
> echo 'Navigate to http://localhost:1337/demo/iframe/index.htm or http://localhost:1337/demo/popup/index.htm' && serve . --port 1337 --silent

'Navigate to http://localhost:1337/demo/iframe/index.htm or http://localhost:1337/demo/popup/index.htm'
'serve' is not recognized as an internal or external command,
operable program or batch file.
```

Because of this I'm unable to run the demo.

**Comment by daton89** [comment]
you should install `serve` package like this: 
`npm install -D serve`
and update the demo script in `package.json` to `..... && serve . -l 1337`

**Comment by Guru-Work** [comment]
yup that works, see the git diff below

-    "demo": "echo 'Navigate to http://localhost:1337/demo/iframe/index.htm or http://localhost:1337/demo/popup/index.htm' && serve . --port 1337 --silent",
+    "demo": "echo 'Navigate to http://localhost:1337/demo/iframe/index.htm or http://localhost:1337/demo/popup/index.htm' && serve . -l 1337",

**Comment by bluepnume** [comment]
Fixed.
